url: http://dringtech.com
baseurl:

# Site settings
title: Dring Technology Solutions
email: giles@dringtech.com
description: Enterprise IT thinking for Small and Medium Businesses
author: dringtech
twitter:
  username: dringtech
logo: img/dringtech-compact.png

googleAnalyticsId: UA-60515978-1

include:
  - .well-known

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

social:
  - title: twitter
    url: https://twitter.com/dringtech
  - title: facebook
    url: https://facebook.com/dringtech/
  - title: github
    url: https://github.com/dringtech
  - title: linkedin
    url: https://linkedin.com/company/dring-technology-solutions-limited

exclude:
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - package.json
  - package_lock.json

# Postal address (add as many lines as necessary)
address:
  - line: 13 Melbourne Street
  - line: Hebden Bridge
  - line: West Yorkshire

# Build settings
markdown: kramdown
permalink: pretty

# HTML Compression using https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: all

collections:
  sections:
    output: false
  services:
    output: true

defaults:
  - scope:
      path: ""
      type: sections
    values:
      enabled: true
      nav: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
