url: http://dringtech.github.io
baseurl:

# Site settings
title: Dring Tech
email: giles@dringtech.com
description: "Dring Technology Solutions Limited: Enterprise IT thinking for Small Businesses. Bringing 20 years of IT strategy and implementation expertise to Small and Medium Enterprises."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/dringtech
  - title: facebook
    url: https://facebook.com/dringtech/
  - title: github
    url: https://github.com/dringtech
  - title: linkedin
    url: https://linkedin.com/company/dring-technology-solutions-limited

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
