backend:
  name: github
  repo: dringtech/dringtech.github.io
  base_url: https://kltfd8s7m9.execute-api.eu-west-2.amazonaws.com
  auth_endpoint: prod/auth

media_folder: img/uploads

collections:
  - name: posts # Used in routes, e.g., /admin/collections/posts
    label: Blog # Used in the UI
    label_singular:  Post
    folder: _posts/ # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview_path_date_field: date
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      # - label: Author
      #   name: author
      #   widget: relation
      #   collection: team
      #   displayFields: display_name
      #   searchFields: display_name
      #   valueField: name
      #   multiple: true
      - label: Publish Date
        name: date
        default: ""
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss Z"
        dateFormat: LL
      - label: Featured Image
        required: false
        name: thumbnail
        widget: image
      - label: Body
        name: body
        widget: markdown
